// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentTracker.Data;

#nullable disable

namespace StudentTracker.Data.Migrations
{
    [DbContext(typeof(StudentTrackerDbContext))]
    [Migration("20260828014253_AddCoursePricingAndPoolRouting")]
    partial class AddCoursePricingAndPoolRouting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("StudentTracker.Core.Models.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BillableDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BudgetPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CashCommitmentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CertificateCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateDeliveryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateOrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExportedInBatchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacyReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OutcomeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeNotes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutcomeReasonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceholderName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPoolId");

                    b.HasIndex("CourseDeliveryId");

                    b.HasIndex("CreditPoolId");

                    b.HasIndex("OutcomeReasonId");

                    b.HasIndex("StudentId", "CourseDeliveryId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillableTrigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyLogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataRootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAuthorisedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAuthorisedByPosition")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultBudgetPoolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCreditPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTrainerBusinessDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTrainerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVerifiedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVerifiedByPosition")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryIdSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpenseTrigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoicerExchangeLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportFooter")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignOffDeclarationText")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentIdSeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityDisplayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.BudgetPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinancialPeriod")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BudgetPools");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.BudgetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FundingSourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("FundingSourceId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PoolId");

                    b.ToTable("BudgetTransactions");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateCreditPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CertificateCreditPools");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateCreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalCourseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPurchaseReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ExternalTransactionId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("LinkedTransactionId");

                    b.HasIndex("PoolId");

                    b.ToTable("CertificateCreditTransactions");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveredTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidenceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateOrderId");

                    b.HasIndex("EvidenceDocumentId");

                    b.ToTable("CertificateDeliveries");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderBatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacementReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("CreditTransactionId");

                    b.ToTable("CertificateOrders");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CourseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultCertificateCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultCreditQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchKey");

                    b.ToTable("CourseDefinitions");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CourseDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CourseDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerBusinessDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseDefinitionId");

                    b.ToTable("CourseDeliveries");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CoursePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CompletionPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseDefinitionId", "EffectiveFrom");

                    b.ToTable("CoursePrices");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidentiality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.DocumentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkPurpose")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("DocumentLinks");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.ExportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExportBatches");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.ExportBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ExportBatchId");

                    b.ToTable("ExportBatchItems");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.FundingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FundingSources");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.ImportReviewQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSheet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportReviewQueues");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AmountAssignedToStudentTracker")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalInvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GSTAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileDocumentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.OutcomeReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresNotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutcomeReasons");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.SignOff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorisedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorisedByPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthorisedSignedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrainerSignedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedByName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedByPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedSignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseDeliveryId");

                    b.HasIndex("FileDocumentId");

                    b.ToTable("SignOffs");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.SignOffParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryDateText")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SignOffId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("SignOffId");

                    b.ToTable("SignOffParticipants");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Employer")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupTag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PotentialDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PreferredName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("USI")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkGroup")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.Allocation", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.BudgetPool", "BudgetPool")
                        .WithMany()
                        .HasForeignKey("BudgetPoolId");

                    b.HasOne("StudentTracker.Core.Models.CourseDelivery", "CourseDelivery")
                        .WithMany()
                        .HasForeignKey("CourseDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentTracker.Core.Models.CertificateCreditPool", "CreditPool")
                        .WithMany()
                        .HasForeignKey("CreditPoolId");

                    b.HasOne("StudentTracker.Core.Models.OutcomeReason", "OutcomeReason")
                        .WithMany()
                        .HasForeignKey("OutcomeReasonId");

                    b.HasOne("StudentTracker.Core.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("BudgetPool");

                    b.Navigation("CourseDelivery");

                    b.Navigation("CreditPool");

                    b.Navigation("OutcomeReason");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.BudgetTransaction", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId");

                    b.HasOne("StudentTracker.Core.Models.FundingSource", "FundingSource")
                        .WithMany()
                        .HasForeignKey("FundingSourceId");

                    b.HasOne("StudentTracker.Core.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("StudentTracker.Core.Models.BudgetPool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("FundingSource");

                    b.Navigation("Invoice");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateCreditTransaction", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId");

                    b.HasOne("StudentTracker.Core.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("StudentTracker.Core.Models.CertificateCreditTransaction", "LinkedTransaction")
                        .WithMany()
                        .HasForeignKey("LinkedTransactionId");

                    b.HasOne("StudentTracker.Core.Models.CertificateCreditPool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("Invoice");

                    b.Navigation("LinkedTransaction");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateDelivery", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.CertificateOrder", "CertificateOrder")
                        .WithMany()
                        .HasForeignKey("CertificateOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentTracker.Core.Models.Document", "EvidenceDocument")
                        .WithMany()
                        .HasForeignKey("EvidenceDocumentId");

                    b.Navigation("CertificateOrder");

                    b.Navigation("EvidenceDocument");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CertificateOrder", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentTracker.Core.Models.CertificateCreditTransaction", "CreditTransaction")
                        .WithMany()
                        .HasForeignKey("CreditTransactionId");

                    b.Navigation("Allocation");

                    b.Navigation("CreditTransaction");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CourseDelivery", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.CourseDefinition", "CourseDefinition")
                        .WithMany()
                        .HasForeignKey("CourseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseDefinition");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.CoursePrice", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.CourseDefinition", "CourseDefinition")
                        .WithMany()
                        .HasForeignKey("CourseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseDefinition");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.DocumentLink", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Document", "Document")
                        .WithMany("Links")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.ExportBatchItem", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentTracker.Core.Models.ExportBatch", "ExportBatch")
                        .WithMany("Items")
                        .HasForeignKey("ExportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("ExportBatch");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.Invoice", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Document", "FileDocument")
                        .WithMany()
                        .HasForeignKey("FileDocumentId");

                    b.Navigation("FileDocument");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.SignOff", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.CourseDelivery", "CourseDelivery")
                        .WithMany()
                        .HasForeignKey("CourseDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentTracker.Core.Models.Document", "FileDocument")
                        .WithMany()
                        .HasForeignKey("FileDocumentId");

                    b.Navigation("CourseDelivery");

                    b.Navigation("FileDocument");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.SignOffParticipant", b =>
                {
                    b.HasOne("StudentTracker.Core.Models.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId");

                    b.HasOne("StudentTracker.Core.Models.SignOff", "SignOff")
                        .WithMany("Participants")
                        .HasForeignKey("SignOffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("SignOff");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.Document", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.ExportBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StudentTracker.Core.Models.SignOff", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
